const makers = [
  {
    name: 'Devon Wolfkiel',
    image: 'devon.jpg',
    imageX: 'devonX.jpg',
    title: 'Software Engineer',
    pronouns: 'they/she',
    bio: "Devon Wolfkiel is a full stack software engineer compelled by curiosity and collaborative tech. They have a deep appreciation for the weird, the meta, and the ambiguous. They love word processors more than one might expect, and can't stop trying to build them.",
    linkedIn: 'https://www.linkedin.com/in/devon-wolfkiel/',
    github: 'https://github.com/devon-wolf',
    portfolio: 'https://devon-wolf.github.io/portfolio/bio/',
  },
  {
    name: 'Julianne Vela',
    image: 'juli.jpg',
    imageX: 'juliX.jpg',
    title: 'Software Engineer',
    pronouns: 'she/her',
    bio: "Juli is a Full Stack Software Engineer with a passion for learning and making the world a better place. She is fasinated by science and astronomy and would love to merge her two passions one day! Juli's favorite corporate supply is a nice crisp ream of bright white paper.",
    linkedIn: 'https://www.linkedin.com/in/juliannevela',
    github: 'https://github.com/juliannevela',
    portfolio: 'https://juliannevela.dev',
  },
  {
    name: 'Cameron Zimmerman',
    image: 'cameron.jpg',
    imageX: 'cameronX.jpg',
    title: 'Software Engineer',
    pronouns: 'he/him',
    bio: "Cameron Zimmerman is energetic and positive force for your next team; It is his mission to embody and explore the human and technical sides of software. Cameron believes one's frame of mind has the ability to make or break their work environment, as well as their code. Cameron loves a nice, corporate tan color scheme.",
    linkedIn: 'https://www.linkedin.com/in/cameron-zimmerman/',
    github: 'https://github.com/CameronZimmerman',
  },
  {
    name: 'Katrina Cloyd',
    image: 'katrina.jpg',
    imageX: 'katrinaX.jpg',
    title: 'Software Engineer',
    pronouns: 'she/her',
    bio: 'Katrina Cloyd is a full stack software engineer with a soft spot for the front end. She loves problem-solving and collaborating to find unique solutions from fresh perspectives. She also has a collection of post-it notes in every color.',
    linkedIn: 'https://www.linkedin.com/in/katrinacloyd/',
    github: 'https://github.com/KatrinaCloyd',
  },
  {
    name: 'Casey Warren',
    image: 'casey.jpg',
    imageX: 'caseyX.jpg',
    title: 'Software Engineer',
    pronouns: 'she/her',
    bio: 'Casey Warren is a full stack software developer with a love for design and creativity on the front end. Her favorite type of pen is the Pentel RSVP pens, preferably one of each color.',
    linkedIn: 'https://www.linkedin.com/in/casey-maynah-warren/',
    github: 'https://github.com/caseywar',
  },
];

export default makers;
